### PR TITLE
Refreshed Horizon theme

### PR DESCRIPTION
**Pull request by mkarpiarz**
Our Horizon branding refreshed based on the "Paper" Bootswatch theme.
Also changes the way the path to the theme was handled.

Mind that this only includes variables/styles that were overwritten from
the base theme.

I left the old `params.pp` even though we don't use it - let me know if
you want me to remove it or move system-specific part of the path there.

Please comment if you have suggestions regarding the feel and look of
the theme and you want me to change anything.

Part of PD-2992.

### CODE REVIEW

**Comment by mkarpiarz** [comment]
Screenshots:
screencapture-horizon-auth-login-1500566164725
screencapture-horizon-project-1500566188255
screencapture-horizon-project-1500566540103
screencapture-horizon-project-cgroups-1500566267247
screencapture-horizon-project-instances-1500566206273
screencapture-horizon-project-instances-1500566246290
screencapture-horizon-project-network_topology-1500566294324

**Comment by miklasz** [comment]
is it possible to add little icon next to IP address, and when u click it it will copy ip to clipboard ? :)
screen shot 2017-07-20 at 17 40 57

**Comment by mkarpiarz** [comment]
This is not possible by just editing the theme. IP addresses are represented as just plain text, so there is no way this button would know what to copy, not without writing a custom dashboard or some JavaScript wizardry. ;)

**Review by spjmurray — APPROVED** [review]
Masthead logo looks perhaps a little too big, but that's subjective and we can always tweak it later once I have a play in real life :)

**Comment by mkarpiarz** [comment]
Felt the same about the logo myself, @spjmurray, and I tried to reduce the height of the whole navbar. Sadly, the `$navbar-height` variable controls min-height and these dropdowns within the navbar refuse to shrink. I left this as it is for now but, yeah, we can try to adjust the height later.

**Review by yankcrime — APPROVED** [review]
Awww yissss

**Pull request merged**
